### PR TITLE
add links around twitter, GitHub, homepage

### LINKED ISSUE #4: Add links around supplied info
When running the cli, it asks for your site, twitter, GitHub, and those are added in the created slides, but they aren't links. I think it'd be nice if they are also available as links by default.

### PR DESCRIPTION
**Pull request by Haroenv**
Also there should be a check around each of them, if the user supplied it (like you do with twitter in the header manually).

Maybe just use a templating engine like moustache?

fixes #4

### CODE REVIEW

**Comment by reimertz** [comment]
Man, getting help 2 hours after releasing the beta. You are awesome.

Would it be a hassle investigating the complexity of adding mustach/handlebars/etc instead?
If you don't have the time, I am more than glad to merge this.

**Comment by Haroenv** [comment]
I'll take a look which seems most suitable

**Comment by Haroenv** [comment]
According to https://garann.github.io/template-chooser/, I'd use https://github.com/janl/mustache.js/, since it's Mustache, thus more widely known. Handlebars seems to add more things, but that also makes it complicated. In this case we'd use:

```html
{#twitter}
  <p>twitter: <a href="//twitter.com/{{twitter}}">{{twitter}}</a></p>
{/twitter}
```

As seen [here](https://mustache.github.io/mustache.5.html)

Asking the render should be like this:

```js
Mustache.render('get this from the index file', {data});
```

**Comment by Haroenv** [comment]
Anyway, this pull request can be merged before deciding on a templating system, since it'll stay the same. 

P.S. another options is [liquid-node](https://github.com/sirlantis/liquid-node), if you prefer that syntax (like Jekyll)

**Pull request merged**
